DynamicForms/Models/Field.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DynamicForms.Models
{
	public class Field
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int FieldID { get; set; }

		public string Description { get; set; }

		public int TypeID { get; set; }

		public int ValueTypeID { get; set; }

		public virtual ICollection<Form> Forms { get; set; }
	}
}

DynamicForms/Models/Form.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DynamicForms.Models
{
	public class Form
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int FormID { get; set; }

		public string Name { get; set; }

		public DateTime? StartingValidity { get; set; }

		public DateTime? EndingValidity { get; set; }

		public virtual ICollection<Field> Fields { get; set; }
	}
}

DynamicForms/Models/Type.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DynamicForms.Models
{
	public class Type
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int TypeID { get; set; }

		public string Description { get; set; }
	}
}

DynamicForms/Models/ValueType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DynamicForms.Models
{
	public class ValueType
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int ValueTypeID { get; set; }

		public string Description { get; set; }

		public int TypeID { get; set; }

		public virtual Type Type { get; set; }
	}
}

DynamicForms/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DynamicForms.DAL;
using DynamicForms.Models;
using FormContext = DynamicForms.DAL.FormContext;
using PagedList;
using Newtonsoft.Json;
using System.Data.Entity.Migrations;

namespace DynamicForms.Controllers
{
    public class FormsController : Controller
    {
		private FormContext db = new FormContext();

        // GET: Forms/Index
        public ActionResult Index()
        {
			return View(db.Forms.ToList());
        }

		// GET: Forms/List
		public ActionResult List(int? selectedStatus, string sortOrder, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			ViewBag.StartingValiditySortParm = String.IsNullOrEmpty(sortOrder) ? "start_valid_desc" : "";
			ViewBag.EndingValiditySortParm = String.IsNullOrEmpty(sortOrder) ? "end_valid_desc" : "";
			ViewBag.SelectedStatusID = selectedStatus.GetValueOrDefault();

			ViewBag.SelectedStatus = new SelectList(
				new List<SelectListItem>
				{
					new SelectListItem { Selected = false, Text = "Ativo", Value = "1"},
					new SelectListItem { Selected = false, Text = "Inativo", Value = "2"},
				}, "Value", "Text", selectedStatus);

			List<Form> forms = new List<Form>();
			if (!selectedStatus.HasValue || selectedStatus == 0)
				forms = db.Forms.ToList();
			else if (selectedStatus == 1)
				forms = db.Forms.
					Where(c => c.StartingValidity <= DateTime.Now && c.EndingValidity >= DateTime.Now).ToList();
			else
				forms = db.Forms.
					Where(c => c.StartingValidity > DateTime.Now || c.EndingValidity < DateTime.Now).ToList();

			switch (sortOrder)
			{
				case "name_desc":
					forms = forms.OrderByDescending(s => s.Name).ToList();
					break;
				case "start_valid_desc":
					forms = forms.OrderBy(s => s.StartingValidity).ToList();
					break;
				case "end_valid_desc":
					forms = forms.OrderByDescending(s => s.EndingValidity).ToList();
					break;
				default:
					forms = forms.OrderBy(s => s.Name).ToList();
					break;
			}

			int pageSize = 10;
			int pageNumber = (page ?? 1);
			return View(forms.ToPagedList(pageNumber, pageSize));
		}

		public JsonResult GetItem(int? id)
		{
			if (id == null)
			{
				return Json(new { success = false });
			}
			Form form = db.Forms.Find(id);
			if (form == null)
			{
				return Json(new { success = false });
			}

			return Json(JsonConvert.SerializeObject(form,
				new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore }),
				JsonRequestBehavior.AllowGet);
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public JsonResult Create(Form form)
		{
			if (ModelState.IsValid)
			{
				db.Forms.Add(form);
				db.SaveChanges();

				var RedirectUrl = Url.Action("Index", "Home");
				return Json(new { success = true, redirectUrl = RedirectUrl });
			}
			return Json(new
			{
				success = false
			});
		}

		[HttpPost]
		public JsonResult Edit(Form form)
		{
			if (ModelState.IsValid)
			{
				var formDb = db.Forms.Find(form.FormID);

				if (TryUpdateModel(formDb, "",
					new string[] { "Name", "StartingValidity", "EndingValidity", "Fields" }))
				{
					try
					{
						db.SaveChanges();

						var RedirectUrl = Url.Action("Index", "Home");
						return Json(new { success = true, redirectUrl = RedirectUrl });
					}
					catch
					{
						return Json(new { success = false });
					}
				}
			}
			return Json(new { success = false });
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

DynamicForms/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DynamicForms.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

DynamicForms/Controllers/TypesController.cs
using Newtonsoft.Json;
using System.Linq;
using System.Web.Mvc;
using FormContext = DynamicForms.DAL.FormContext;

namespace DynamicForms.Controllers
{
	public class TypesController : Controller
    {
        private FormContext db = new FormContext();

        // GET: Types
        public ActionResult Index()
        {
            return View(db.Types.ToList());
        }

		public ActionResult GetTypes()
		{
			var types = JsonConvert.SerializeObject(db.Types.ToList(), 
				new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

			return Json(types, JsonRequestBehavior.AllowGet);
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

DynamicForms/Controllers/ValueTypesController.cs
using Newtonsoft.Json;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using FormContext = DynamicForms.DAL.FormContext;

namespace DynamicForms.Controllers
{
	public class ValueTypesController : Controller
    {
        private FormContext db = new FormContext();

        // GET: ValueTypes
        public ActionResult Index()
        {
            return View(db.ValueTypes.ToList());
        }

		public ActionResult GetValueTypesByTypeId(int typeId)
		{
			var valueTypes = 
				JsonConvert.SerializeObject(db.ValueTypes.Where(v => v.TypeID == typeId).ToList());

			return Json(valueTypes, JsonRequestBehavior.AllowGet);
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

DynamicForms/Views/Forms/Create.cshtml
@{
    ViewBag.Title = "Form";
}

<div id="content" ng-controller="FormController">
    <h2>{{FormName}} Form</h2>

    <div ng-class="result">{{message}}</div>
    <hr />
    <form ng-submit="submitForm()" name="frmForm">
        <div>
            <label for="name">Nome</label>
            <input type="text" ng-model="form.Name" name="name" required ng-minlength="4" ng-maxlength="14" />
        </div>

        <br />

        <div>
            <div>
                <label>Campos</label>
                <p>
                    <button type="button" ng-click="addNewField()">Adicionar campo</button>
                </p>

                <p>Total de campos (10 no mínimo): {{form.Fields.length}}</p>
            </div>

            <div class="form-group" data-ng-repeat="field in form.Fields">
                <div>
                    <label for="description">Descrição</label>
                    <input type="text" ng-model="field.Description" name="description" required />

                    <label for="type">Tipo</label>
                    <select ng-init="field.TypeID = setTypeId(field.TypeID, $index)"
                            ng-model="field.TypeID"
                            ng-options="type.TypeID as type.Description for type in types"
                            ng-change="getValueTypesByType(field.TypeID, $index)" required>
                        <option value="">Selecione um tipo</option>
                    </select>

                    <label for="valueType">Tipo do Valor</label>
                    <select ng-model="field.ValueTypeID"
                            ng-options="valueType.ValueTypeID as valueType.Description for valueType in valueTypes[$index]" required>
                        <option value="">Selecione um tipo de valor</option>
                    </select>

                    <button type="button" ng-click="removeField($index)">Remover campo</button>
                </div>
            </div>
        </div>

        <br />

        <div>
            <label>Vigência</label>

            <div>
                <label for="name">Início:</label>
                <input type="date" ng-model="form.StartingValidity" name="startingValidity" startdate />

                <label for="name">Fim:</label>
                <input type="date" ng-model="form.EndingValidity" name="endingValidity" enddate />

                <div ng-show="frmForm.startingValidity.$dirty && frmForm.startingValidity.$error.startdate">A data inicial deve ser maior que a data atual</div>
                <div ng-show="frmForm.endingValidity.$dirty && frmForm.endingValidity.$error.enddate">A data final não pode ser inferior à inicial</div>
            </div>
        </div>

        <br />

        <div>
            <button type="submit" ng-disabled="customValidity(frmForm)">Salvar</button>
        </div>
    </form>
</div>

DynamicForms/Views/Forms/List.cshtml
@model PagedList.IPagedList<DynamicForms.Models.Form>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Lista";
}

<h2>Lista</h2>

@using (Html.BeginForm("List", "Forms", FormMethod.Get))
{
    <p>
        Status do Formulário: @Html.DropDownList("SelectedStatus", "Todos")
        <input type="submit" value="Filtrar" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Nome", "List", new { selectedStatus = ViewBag.SelectedStatusID, sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            @Html.ActionLink("Vigência: Início", "List", new { selectedStatus = ViewBag.SelectedStatusID, sortOrder = ViewBag.StartingValiditySortParm })
        </th>
        <th>
            @Html.ActionLink("Vigência: Fim", "List", new { selectedStatus = ViewBag.SelectedStatusID, sortOrder = ViewBag.EndingValiditySortParm })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartingValidity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndingValidity)
            </td>
            <td>
                @Html.ActionLink("Editar", "Create", new { id = item.FormID })
            </td>
        </tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("List",
    new { selectedStatus = ViewBag.SelectedStatusID, sortOrder = ViewBag.CurrentSort, page }))

DynamicForms/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Form App";
}

<p>
<p>
    @Html.ActionLink("Criar Form", "Create", "Forms")
</p>
<p>
    @Html.ActionLink("Listar Forms", "List", "Forms")
</p>
</p>

DynamicForms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="FormApp">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Form App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Criar form", "Create", "Forms")</li>
                    <li>@Html.ActionLink("Listar forms", "List", "Forms")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/controllersNg")
    @RenderSection("scripts", required: false)
</body>
</html>